name:                haskell-optics
version:             0.1.0.0
github:              "williamdemeo/haskell-optics"
license:             BSD3
author:              "William DeMeo"
maintainer:          "williamdemeo@gmail.com"
copyright:           "2021 William DeMeo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/williamdemeo/haskell-optics#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- lens
- lens-aeson
- mtl
- text

library:
  source-dirs: src

executables:
  haskell-optics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-optics

tests:
  haskell-optics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-optics
